fix(user-location): fix crash issue when using androidRenderMode
react-native-mapbox-gl/maps pull request #1026
Opened 2020-09-11 12:06 UTC by ferdicus

App crashes when user is trying to set `androidRenderMode` as described in issue #1022.

I think I've tracked it down to a missing non-null check in `NativeUserLocation`.
In `setRenderMode` it attempts to call `getLocationComponentManager` on `mMapView` which seems to be `null` at that point in time.

This change fixes the crash. 

Two more things I noticed though:
* no types for `androidRenderMode` in `index.d.ts` (which I will address with a follow-up PR)
* the heading indicator doesn't seem to change when using `androidRenderMode="compass"`(from the short test I did 🤷 )

Feedback appreciated, thanks 🙇

2020-09-11 12:25 UTC, mfazekas requested changes
👍

2020-09-11 12:25 UTC, mfazekas commented on android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java
> +        if (mMap != null) {
I think we might want to emit some error.  As the renderMode change will be lost in such case. (Either we need to store the desired mode and set when the map is attached. When logging please use `com.mapbox.mapboxsdk.log.Logger` as that gets transferred to js side.

2020-09-11 13:01 UTC, ClayC-WeatherBug commented on android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java
> +        if (mMap != null) {
Any idea on the cause of why mMap is null when setRenderMode is being called?

2020-09-11 13:06 UTC, ferdicus commented on android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java
> +        if (mMap != null) {
@mfazekas, just want to make sure I understand it correctly. 
If I should log when `mMap != null`, then it would mean we would indeed have an error every time `androidRenderMode` is used.

I was able to reproduce this 100% without much hassle. 

Wouldn't this be super annoying?

Maybe I'm mistaken

2020-09-11 13:07 UTC, ferdicus commented on android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java
> +        if (mMap != null) {
@ClayC-WeatherBug:
Unsure what is causing this - I would assume there are all sorts of race conditions happening. 🤷‍♂️ 
We have quite some `mMap == null` checks in source unfortunately :(

2020-09-11 13:10 UTC, ClayC-WeatherBug commented on android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java
> +        if (mMap != null) {
Ah dang - okay that makes sense. So this will get called repeatedly until mMap is not null and then it will set the render mode?

2020-09-11 13:26 UTC, ferdicus commented on android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java
> +        if (mMap != null) {
> Ah dang - okay that makes sense. So this will get called repeatedly until mMap is not null and then it will set the render mode?

yes... hopefully :D

2020-09-11 13:42 UTC, ClayC-WeatherBug commented on android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java
> +        if (mMap != null) {
Works for me 👍

2020-09-11 13:42 UTC, ClayC-WeatherBug approved these changes

2020-09-14 07:05 UTC, mfazekas commented on android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java
> +        if (mMap != null) {
So first react builds the components, the compontents added to parent MapView, at that point `mMapView` becomes non-null, and later when the Mapbox map in map view is initialized onMapReady is called and `mMap` becomes non-null.

But looking at the crash the reason for the crash is because `mMapView` is null, but this fix checks for `mMap`, why?!

2020-09-14 07:28 UTC, ferdicus commented on android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java
> +        if (mMap != null) {
yeah, you're right - I checked for map indiscriminately, should be more specific.

2020-09-25 08:21 UTC, mfazekas requested changes

2020-09-25 08:21 UTC, mfazekas commented on android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java
> +        if (mMapView != null) {
If we don't have mMapView we should store `renderMode` in a variable and set it when we finally have `MapView`. Otherwise it'll be just lost.

2020-09-25 08:28 UTC, ferdicus commented on android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java
> +        if (mMapView != null) {
Thanks, where do you think would be a good spot to do that?

Should I maybe check in `#addToMap` if we have a `renderMode` set and then call `#setRenderMode` with it?
Or is there a better approach?

2020-09-25 08:42 UTC, mfazekas commented on android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java
> +        if (mMapView != null) {
Yep i think `addToMap` would be a good place to check. We have something similar with `RCTMGLCamera` with `MaxBounds` for example.


https://github.com/react-native-mapbox-gl/maps/blob/189213ffdf21ce47705eb809f24e44a1ed772de8/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/RCTMGLCamera.java#L128-L133

https://github.com/react-native-mapbox-gl/maps/blob/189213ffdf21ce47705eb809f24e44a1ed772de8/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/RCTMGLCamera.java#L167-L177

https://github.com/react-native-mapbox-gl/maps/blob/189213ffdf21ce47705eb809f24e44a1ed772de8/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/RCTMGLCameraManager.java#L56-L62

2020-09-25 12:42 UTC, mfazekas requested changes
Looks great, but i think there is a typo

2020-09-25 12:42 UTC, mfazekas commented on android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java
> +        if (mRenderMode < 0) { setRenderMode(mRenderMode); }
```suggestion
        if (mRenderMode >= 0) { setRenderMode(mRenderMode); }
```

2020-09-25 12:45 UTC, ferdicus commented on android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java
> +        if (mRenderMode < 0) { setRenderMode(mRenderMode); }
🤦‍♂️

2020-09-25 12:49 UTC, ferdicus commented
Can you please have another look. 

Quick question, always eager to learn over here:
I had to loosen the type a bit, in order to initialize the int with `-1` which is not defined in `RenderMode`
Would there have been another way to do this, without losing `@RenderMode.Mode`?

2020-09-25 13:13 UTC, mfazekas commented
> Quick question, always eager to learn over here:
> I had to loosen the type a bit, in order to initialize the int with `-1` which is not defined in `RenderMode`
> Would there have been another way to do this, without losing `@RenderMode.Mode`?

I'm not a java expert so not 100% on this. 

You might be able to use java.lang.Integer which allows null. 
Or just use a default - note sure what's would be appropriate in this case.

2020-09-25 13:58 UTC, ferdicus commented
I'm going with this:
> Or just use a default - note sure what's would be appropriate in this case.

We're doing something similar [here](https://github.com/react-native-mapbox-gl/maps/blob/master/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/LocationComponentManager.java#L37)

keeps type in tact

2020-09-25 14:07 UTC, mfazekas commented on android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java
> +        if (mRenderMode >= 0) { setRenderMode(mRenderMode); }
```suggestion
       setRenderMode(mRenderMode);
```

2020-09-25 14:56 UTC, mfazekas approved these changes

2020-09-25 16:01 UTC, ferdicus commented on android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java
> +        if (mRenderMode >= 0) { setRenderMode(mRenderMode); }
😭

2020-09-25 16:01 UTC, merged