fix(image-source): dynamically update ImageSource coordinates
react-native-mapbox-gl/maps pull request #1036
Opened 2020-09-18 16:26 UTC by ferdicus

This fixes #1013, however only the Android portion as I'm an even bigger noob in Objective-C than in Java :(

Maybe someone with an inkling of iOS development experience could have a look and finish the other part?

Cheers

2020-09-25 09:30 UTC, ferdicus commented
@mfazekas, if you find the time, can you have a look at the iOS side of things here please? 

Thanks 🙇

2020-09-25 16:27 UTC, ferdicus commented
@mfazekas, I've added some hacked together code, which gets the job done.
Unfortunately this only seems to work now with the dynamically updating coordinates/ urls, but not with the actual ImageOverlay example 😭 


In order to test this, simple replace the content of `example ImageOverlay.js`
With the code here:


<details> 

```jsx

import React from 'react';
import MapboxGL from '@react-native-mapbox-gl/maps';

import sheet from '../styles/sheet';
import radar0 from '../assets/radar.png';
import radar1 from '../assets/radar1.png';
import radar2 from '../assets/radar2.png';

import Page from './common/Page';
import BaseExamplePropTypes from './common/BaseExamplePropTypes';

const frames = [radar0, radar1, radar2];
const coordQuads = [
  [
    [-80.425, 46.437], // top left
    [-71.516, 46.437], // top right
    [-71.516, 37.936], // bottom right
    [-80.425, 37.936], // bottom left
  ],
  [
    [-85.425, 45.437], // top left
    [-75.516, 45.437], // top right
    [-75.516, 36.936], // bottom right
    [-85.425, 36.936], // bottom left
  ],
];

class ImageOverlay extends React.Component {
  static propTypes = {
    ...BaseExamplePropTypes,
  };

  constructor(props) {
    super(props);

    this.state = {
      radarFrameIndex: 0,
      coords: coordQuads[0],
    };

    this._timeout = null;
  }

  componentDidMount() {
    this.heartbeat();
  }

  heartbeat() {
    this._timeout = setTimeout(() => {
      requestAnimationFrame(() => {
        let nextFrame = this.state.radarFrameIndex + 1;
        if (nextFrame > 1) {
          nextFrame = 0;
        }
        this.setState({radarFrameIndex: nextFrame, coords: coordQuads[nextFrame]})
        this.heartbeat();
      });
    }, 500);
  }

  componentWillUnmount() {
    if (this._timeout) {
      clearTimeout(this._timeout);
    }
  }

  render() {
    return (
      <Page {...this.props}>
        <MapboxGL.MapView
          ref={(ref) => (this.map = ref)}
          style={sheet.matchParent}
          styleURL={MapboxGL.StyleURL.Satellite}>
          <MapboxGL.Camera
            zoomLevel={4}
            centerCoordinate={[-75.789, 41.874]}
          />

          <MapboxGL.Animated.ImageSource
            key="d"
            id="radarSource"
            coordinates={this.state.coords}
            url={frames[this.state.radarFrameIndex]}>
            <MapboxGL.RasterLayer id="radarLayer"
            style={{rasterOpacity: .6}} />
          </MapboxGL.Animated.ImageSource>
        </MapboxGL.MapView>
      </Page>
    );
  }
}

export default ImageOverlay;

```
</details>

Would appreciate some pointers, thanks in advance 🙇

2020-10-02 12:14 UTC, mfazekas requested changes

2020-10-02 12:14 UTC, mfazekas commented on ios/RCTMGL/RCTMGLImageSource.m
> +
```suggestion
- (void)setCoordinates:(NSArray<NSArray<NSNumber *> *> *)coordinates
{
    _coordinates = coordinates;
    if (self.source != nil) {
        MGLImageSource *source = (MGLImageSource *)self.source;
        source.coordinates = [self _makeCoordQuad];
    }
}
```

2020-10-02 12:36 UTC, ferdicus commented on ios/RCTMGL/RCTMGLImageSource.m
> +
Nice, this does it - thanks! 

I'll enhance the example and merge without another review, if you're fine with that. 

Cheers

2020-10-02 12:51 UTC, mfazekas commented on ios/RCTMGL/RCTMGLImageSource.m
> +
Sure fine!

2020-10-02 12:51 UTC, mfazekas commented on ios/RCTMGL/RCTMGLImageSource.m
> +
👍

2020-10-02 13:39 UTC, merged