Prevent padding from exceeding bounds on Android
react-native-mapbox-gl/maps pull request #1072
Opened 2020-10-15 19:22 UTC by naftalibeder

This is essentially a port of the logic that @mfazekas created in #1057 for iOS, which prevents a crash in the event of an 'illegal' layout configuration involving map padding along one axis that exceeds the dimensions of the map in that direction.

For example, if the top and bottom padding exceed the height of the map, this allows it to make a decent guess instead of simply crashing.

More specifically, the logic mirrors what I suggested [here](https://github.com/react-native-mapbox-gl/maps/pull/1057#discussion_r501996207), because I was still having problems with the exact logic in that PR. My justification for handling the error in this way is also detailed in that discussion.

2020-10-16 13:15 UTC, ferdicus reviewed
Looks sane to me comparing to the iOS solution. 

With the different philosophies on gracefully saving when it's exceeding - you guys have to duke that one out between yourselves :)

Once you come to a resolution I'd like it if both solutions were consistent. 

Here for example it reads `overflow` in the iOS solution it's `extra`

Thanks in advance

2020-10-16 16:24 UTC, mfazekas requested changes
👍 

let sync the alg to the one used in ios

2020-10-16 16:24 UTC, mfazekas commented on android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/CameraStop.java
> +            bottom -= overflow / 2.0 + 1;
```suggestion
            double overflow =  top + bottom - height + 1.0;
            top -= overflow * top / (top + bottom);
            bottom -= overflow * bottom / (top + bottom);
```

2020-10-16 16:24 UTC, mfazekas commented on android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/CameraStop.java
> +            right -= overflow / 2.0 + 1;
```suggestion
            double overflow =  left + right - width + 1.0;
            left -= overflow * left / (left + right);
            right -= overflow * right / (left + right);
```

2020-10-19 15:01 UTC, mfazekas approved these changes

2020-10-20 10:16 UTC, closed without merging