Issue 915: Stop/start Location manager based on listeners registered.
react-native-mapbox-gl/maps pull request #999
Opened 2020-08-23 09:43 UTC by soumyashisPR

**Issue**: react-native-mapbox-gl https://github.com/react-native-mapbox-gl/maps/issues/915
This issue was caused by UserLocation component as it was stopping the locationManager, which can be shared by other UserLocation instances.

**Fix**:
'UserLocation' should only add/remove its listener on 'locationManager' service and never start or stop it. It the responsibility of the locationManager to start or stop itself depending on the number of listeners registered.
1. Removed code to start/stop locationManager from UserLocation component.
2. Added code to start/stop the LocationManager within LocationManager component itself, based on number of listeners registered at the moment.

------

EDIT ferdicus: 
resolves #915

2020-08-26 08:55 UTC, soumyashisPR commented
@mfazekas Would you be able to have a look at the PR? 
Thanks.

2020-08-27 06:15 UTC, mfazekas requested changes
👍 Thanks, nice work.
It would be great if you could summarise the issues fixed with the changes. 

There are also some rename, which is not backward compatible. If the new names are better i'm all for it, but we must keep old versions working and showing a deprecation alert.

2020-08-27 06:15 UTC, mfazekas commented on docs/UserLocation.md
> -#### setLocationManager({running})
This seems to be a breaking change, which means this could be merged into next major release. And we'll need a warning if they pass the old key `running`

2020-08-27 06:15 UTC, mfazekas commented on javascript/components/UserLocation.js
> -    locationManager.removeListener(this._onLocationUpdate);
what happened with `removeListener` !?

2020-08-27 06:15 UTC, mfazekas commented on javascript/modules/location/locationManager.js
> -      if (this._lastKnownLocation) {
why was this removed?!

2020-08-28 12:38 UTC, ferdicus reviewed
Thanks for tackling this, just added some comments.

Besides fixing failing tests it would be great if you would kindly add additional tests covering your changes. 

🙇

2020-08-28 12:38 UTC, ferdicus commented on __tests__/components/UserLocation.test.js
> +      });
I know this got introduced in other tests, however it seemed to work without it before. 
What changed?

2020-08-28 12:38 UTC, ferdicus commented on __tests__/modules/location/locationManager.test.js
> +
why not test for it being called/ not called when you already added a jest mock?

2020-08-28 12:38 UTC, ferdicus commented on javascript/components/UserLocation.js
> +  isLocationManagerRequired() {
maybe we could chose a different name here? 
It's awfully close to `_isLocationManagerRequired`

2020-09-11 10:17 UTC, ferdicus commented
@soumyashisPR, did you find the time to check the review comments?

Thanks 🙇

2020-09-12 15:07 UTC, soumyashisPR commented on javascript/components/UserLocation.js
> -    locationManager.removeListener(this._onLocationUpdate);
listener is removed/added in setLocationManager method, based on boolean 'required'.

2020-09-12 15:09 UTC, soumyashisPR commented on __tests__/modules/location/locationManager.test.js
> +
Added.

2020-09-12 15:31 UTC, soumyashisPR commented on docs/UserLocation.md
> -#### setLocationManager({running})
Hey @mfazekas , could you please guide me how we can handle this ?
I didn't follow how this would be a breaking change.

2020-09-12 15:40 UTC, soumyashisPR commented
Hey @ferdicus , have addressed the review comments. Let me know if there are further changes required. 
Currently stuck with some failing unit tests and unable to figure out the issue there.
Would be great if I could get some help / guidance.
Thanks

2020-09-18 08:48 UTC, ferdicus commented on javascript/components/UserLocation.js
> -        const location = await locationManager.getLastKnownLocation();
I missed this the last time around, I think you can remove `getLastKnownLocation` then from `locationManager` as it's not being used anymore?

2020-09-18 08:56 UTC, ferdicus commented
> Hey @ferdicus , have addressed the review comments. Let me know if there are further changes required.
> Currently stuck with some failing unit tests and unable to figure out the issue there.
> Would be great if I could get some help / guidance.
> Thanks

Thanks @soumyashisPR, can you please address all comments.  🙇 

Also, what seems to be the issue with the unit tests? 
Could you be more specific? 

Thanks again

2020-09-18 15:09 UTC, mfazekas commented on docs/UserLocation.md
> -#### setLocationManager({running})
My understanding is that before your change one called:
```setLocationManager({running: true})```

after your change:
```setLocationManager({required: true})```

So old code will break with the new libs, won't it?!

As for fixing, i see those options:

1. revert back to `running`
2. use `required` but when old code passes `running` use it as required value and show a warning.

2020-09-22 01:01 UTC, systemlevel commented
Is this PR going to create an issue for us who don't want the Location Manager running at all?  

For example, we are unmounting the <UserLocation /> When we don't want the location manager to run at all when the app is in the background, inactive, or active.

2020-09-22 05:11 UTC, soumyashisPR commented
> Is this PR going to create an issue for us who don't want the Location Manager running at all?
> 
> For example, we are unmounting the `<UserLocation />` when we don't want the location manager to run at all when the app is in the background, inactive, or active.

Hey @systemlevel, according to the PR, unmounting `<UserLocation />` will stop it from listening to the locationManager, it won't stop the location manager, unless it was the only `<UserLocation />`listening to the location manager, in which case it would stop.
Same applies for when `<UserLocation />` is mounted, it will start listening to locationManager, and location manager is started if not already started.

2020-09-22 05:12 UTC, soumyashisPR commented on docs/UserLocation.md
> -#### setLocationManager({running})
Thanks for the suggestions.
Reverted the rename.

2020-09-22 05:20 UTC, soumyashisPR commented on __tests__/components/UserLocation.test.js
> +      });
Have reverted this change.
Had added this as fix to failing unit test.

2020-09-22 05:21 UTC, soumyashisPR commented on javascript/components/UserLocation.js
> +  isLocationManagerRequired() {
Have reverted the rename changes.
Changed to `needsLocationManagerRunning`.

2020-09-22 05:24 UTC, soumyashisPR commented on javascript/components/UserLocation.js
> -        const location = await locationManager.getLastKnownLocation();
Hi, this is actually being used in `setLocationManager` 
`if (running) {
        locationManager.addListener(this._onLocationUpdate);
        const location = await locationManager.getLastKnownLocation();
        this._onLocationUpdate(location);
      } else {
        locationManager.removeListener(this._onLocationUpdate);
      }`

2020-09-22 05:31 UTC, soumyashisPR commented
> > Hey @ferdicus , have addressed the review comments. Let me know if there are further changes required.
> > Currently stuck with some failing unit tests and unable to figure out the issue there.
> > Would be great if I could get some help / guidance.
> > Thanks
> 
> Thanks @soumyashisPR, can you please address all comments. 🙇
> 
> Also, what seems to be the issue with the unit tests?
> Could you be more specific?
> 
> Thanks again

Nevermind, the issue with unit tests is fixed. 

Thanks.

2020-09-25 04:36 UTC, ferdicus commented on javascript/components/UserLocation.js
> -        const location = await locationManager.getLastKnownLocation();
I mean... yeah, now it does after you reverted it again :)

2020-09-29 06:23 UTC, soumyashisPR commented on javascript/modules/location/locationManager.js
> -      if (this._lastKnownLocation) {
Change reverted. 
Reason for removing this, I was trying to keep addListener() and the method call listener() independent, but didn't work out.

2020-10-01 04:29 UTC, soumyashisPR commented on javascript/modules/location/locationManager.js
> -      if (this._lastKnownLocation) {
@mfazekas Please let me know if any more changes are required with this PR.
Thanks.

2020-10-01 05:06 UTC, mfazekas approved these changes

2020-10-01 05:06 UTC, mfazekas commented on __tests__/modules/location/locationManager.test.js
> +      test('does not read same listener', () => {
I think 're-add' make more sense here

2020-10-01 05:07 UTC, mfazekas commented on __tests__/modules/location/locationManager.test.js
> +      test('does not read same listener', () => {
```suggestion
      test('does not readd same listener', () => {
```

2020-10-01 10:17 UTC, soumyashisPR commented on __tests__/modules/location/locationManager.test.js
> +      test('does not read same listener', () => {
Fixed.

2020-10-02 15:47 UTC, ferdicus approved these changes
Thanks @soumyashisPR for this PR and sorry it took a while :)

Lets get this out the door 🚪

2020-10-02 15:50 UTC, merged